version: '3'
services:
  db:
    container_name:  db
    image: mysql
    environment:
      - MYSQL_DATABASE=DockerBraulio
      - MYSQL_ROOT_PASSWORD=1234
  app:
    container_name:  server
    restart: always
    build: .
    ports:
      - '8080:8080'
    depends_on: 
      -  db
    command: ["./wait-for-it.sh", "db:3306", "--", "node", "server.js"]
    environment:
      - PORT=8080